runtime: nodejs10
env_variables:
  SQL_USER: samaritan
  SQL_PASSWORD: "samaritan"
  SQL_DATABASE: "smart_car_park_tobb_etu"
  INSTANCE_CONNECTION_NAME: smart-car-park-api:us-central1:tobb-etu-smart-car-park

beta_settings:
  cloud_sql_instances: smart-car-park-api:us-central1:tobb-etu-smart-car-park
